import "../../styles/fontFacesData.css";

const fontFacesData = {
  Poppins: {
    fontFamily: "Poppins",
    fontPath: "/src/assets/fonts/Poppins/",
    fontData: [
      { filename: "Poppins-Thin", style: "normal", weight: 100 },
      { filename: "Poppins-ExtraLight", style: "normal", weight: 200 },
      { filename: "Poppins-Light", style: "normal", weight: 300 },
      { filename: "Poppins-Regular", style: "normal", weight: 400 },
      { filename: "Poppins-Medium", style: "normal", weight: 500 },
      { filename: "Poppins-SemiBold", style: "normal", weight: 600 },
      { filename: "Poppins-Bold", style: "normal", weight: 700 },
      { filename: "Poppins-ExtraBold", style: "normal", weight: 800 },
      { filename: "Poppins-Black", style: "normal", weight: 900 },
      { filename: "Poppins-ThinItalic", style: "italic", weight: 100 },
      { filename: "Poppins-ExtraLightItalic", style: "italic", weight: 200 },
      { filename: "Poppins-LightItalic", style: "italic", weight: 300 },
      { filename: "Poppins-Italic", style: "italic", weight: 400 },
      { filename: "Poppins-MediumItalic", style: "italic", weight: 500 },
      { filename: "Poppins-SemiBoldItalic", style: "italic", weight: 600 },
      { filename: "Poppins-BoldItalic", style: "italic", weight: 700 },
      { filename: "Poppins-ExtraBoldItalic", style: "italic", weight: 800 },
      { filename: "Poppins-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Rubik: {
    fontFamily: "Rubik",
    fontPath: "/src/assets/fonts/Rubik/static/",
    fontData: [
      { filename: "Rubik-Light", style: "normal", weight: 300 },
      { filename: "Rubik-Regular", style: "normal", weight: 400 },
      { filename: "Rubik-Medium", style: "normal", weight: 500 },
      { filename: "Rubik-SemiBold", style: "normal", weight: 600 },
      { filename: "Rubik-Bold", style: "normal", weight: 700 },
      { filename: "Rubik-ExtraBold", style: "normal", weight: 800 },
      { filename: "Rubik-Black", style: "normal", weight: 900 },
      { filename: "Rubik-LightItalic", style: "italic", weight: 300 },
      { filename: "Rubik-Italic", style: "italic", weight: 400 },
      { filename: "Rubik-MediumItalic", style: "italic", weight: 500 },
      { filename: "Rubik-SemiBoldItalic", style: "italic", weight: 600 },
      { filename: "Rubik-BoldItalic", style: "italic", weight: 700 },
      { filename: "Rubik-ExtraBoldItalic", style: "italic", weight: 800 },
      { filename: "Rubik-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Raleway: {
    fontFamily: "Raleway",
    fontPath: "/src/assets/fonts/Raleway/static/",
    fontData: [
      { filename: "Raleway-Light", style: "normal", weight: 300 },
      { filename: "Raleway-Regular", style: "normal", weight: 400 },
      { filename: "Raleway-Medium", style: "normal", weight: 500 },
      { filename: "Raleway-SemiBold", style: "normal", weight: 600 },
      { filename: "Raleway-Bold", style: "normal", weight: 700 },
      { filename: "Raleway-ExtraBold", style: "normal", weight: 800 },
      { filename: "Raleway-Black", style: "normal", weight: 900 },
      { filename: "Raleway-LightItalic", style: "italic", weight: 300 },
      { filename: "Raleway-Italic", style: "italic", weight: 400 },
      { filename: "Raleway-MediumItalic", style: "italic", weight: 500 },
      { filename: "Raleway-SemiBoldItalic", style: "italic", weight: 600 },
      { filename: "Raleway-BoldItalic", style: "italic", weight: 700 },
      { filename: "Raleway-ExtraBoldItalic", style: "italic", weight: 800 },
      { filename: "Raleway-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Montserrat: {
    fontFamily: "Montserrat",
    fontPath: "/src/assets/fonts/Montserrat/static/",
    fontData: [
      { filename: "Montserrat-Thin", style: "normal", weight: 100 },
      { filename: "Montserrat-ExtraLight", style: "normal", weight: 200 },
      { filename: "Montserrat-Light", style: "normal", weight: 300 },
      { filename: "Montserrat-Regular", style: "normal", weight: 400 },
      { filename: "Montserrat-Medium", style: "normal", weight: 500 },
      { filename: "Montserrat-SemiBold", style: "normal", weight: 600 },
      { filename: "Montserrat-Bold", style: "normal", weight: 700 },
      { filename: "Montserrat-ExtraBold", style: "normal", weight: 800 },
      { filename: "Montserrat-Black", style: "normal", weight: 900 },
      { filename: "Montserrat-ThinItalic", style: "italic", weight: 100 },
      { filename: "Montserrat-ExtraLightItalic", style: "italic", weight: 200 },
      { filename: "Montserrat-LightItalic", style: "italic", weight: 300 },
      { filename: "Montserrat-Italic", style: "italic", weight: 400 },
      { filename: "Montserrat-MediumItalic", style: "italic", weight: 500 },
      { filename: "Montserrat-SemiBoldItalic", style: "italic", weight: 600 },
      { filename: "Montserrat-BoldItalic", style: "italic", weight: 700 },
      { filename: "Montserrat-ExtraBoldItalic", style: "italic", weight: 800 },
      { filename: "Montserrat-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  "Fira Sans": {
    fontFamily: "Fira Sans",
    fontPath: "/src/assets/fonts/Fira_Sans/",
    fontData: [
      { filename: "FiraSans-Thin", style: "normal", weight: 100 },
      { filename: "FiraSans-ExtraLight", style: "normal", weight: 200 },
      { filename: "FiraSans-Light", style: "normal", weight: 300 },
      { filename: "FiraSans-Regular", style: "normal", weight: 400 },
      { filename: "FiraSans-Medium", style: "normal", weight: 500 },
      { filename: "FiraSans-SemiBold", style: "normal", weight: 600 },
      { filename: "FiraSans-Bold", style: "normal", weight: 700 },
      { filename: "FiraSans-ExtraBold", style: "normal", weight: 800 },
      { filename: "FiraSans-Black", style: "normal", weight: 900 },
      { filename: "FiraSans-ThinItalic", style: "italic", weight: 100 },
      {
        filename: "FiraSans-ExtraLightItalic",
        style: "italic",
        weight: 200,
      },
      { filename: "FiraSans-LightItalic", style: "italic", weight: 300 },
      { filename: "FiraSans-Italic", style: "italic", weight: 400 },
      {
        filename: "FiraSans-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "FiraSans-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "FiraSans-BoldItalic", style: "italic", weight: 700 },
      {
        filename: "FiraSans-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      { filename: "FiraSans-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  "Playfair Display": {
    fontFamily: "Playfair Display",
    fontPath: "/src/assets/fonts/Playfair_Display/static/",
    fontData: [
      { filename: "PlayfairDisplay-Regular", style: "normal", weight: 400 },
      { filename: "PlayfairDisplay-Medium", style: "normal", weight: 500 },
      { filename: "PlayfairDisplay-SemiBold", style: "normal", weight: 600 },
      { filename: "PlayfairDisplay-Bold", style: "normal", weight: 700 },
      { filename: "PlayfairDisplay-ExtraBold", style: "normal", weight: 800 },
      { filename: "PlayfairDisplay-Black", style: "normal", weight: 900 },
      { filename: "PlayfairDisplay-Italic", style: "italic", weight: 400 },
      {
        filename: "PlayfairDisplay-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "PlayfairDisplay-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "PlayfairDisplay-BoldItalic", style: "italic", weight: 700 },
      {
        filename: "PlayfairDisplay-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      { filename: "PlayfairDisplay-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Bitter: {
    fontFamily: "Bitter",
    fontPath: "/src/assets/fonts/Bitter/static/",
    fontData: [
      { filename: "Bitter-Thin", style: "normal", weight: 100 },
      { filename: "Bitter-ExtraLight", style: "normal", weight: 200 },
      { filename: "Bitter-Light", style: "normal", weight: 300 },
      { filename: "Bitter-Regular", style: "normal", weight: 400 },
      { filename: "Bitter-Medium", style: "normal", weight: 500 },
      { filename: "Bitter-SemiBold", style: "normal", weight: 600 },
      { filename: "Bitter-Bold", style: "normal", weight: 700 },
      { filename: "Bitter-ExtraBold", style: "normal", weight: 800 },
      { filename: "Bitter-Black", style: "normal", weight: 900 },
      { filename: "Bitter-ThinItalic", style: "italic", weight: 100 },
      {
        filename: "Bitter-ExtraLightItalic",
        style: "italic",
        weight: 200,
      },
      { filename: "Bitter-LightItalic", style: "italic", weight: 300 },
      { filename: "Bitter-Italic", style: "italic", weight: 400 },
      {
        filename: "Bitter-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "Bitter-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "Bitter-BoldItalic", style: "italic", weight: 700 },
      {
        filename: "Bitter-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      { filename: "Bitter-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Lora: {
    fontFamily: "Lora",
    fontPath: "/src/assets/fonts/Lora/static/",
    fontData: [
      { filename: "Lora-Regular", style: "normal", weight: 400 },
      { filename: "Lora-Medium", style: "normal", weight: 500 },
      { filename: "Lora-SemiBold", style: "normal", weight: 600 },
      { filename: "Lora-Bold", style: "normal", weight: 700 },
      { filename: "Lora-Italic", style: "italic", weight: 400 },
      {
        filename: "Lora-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "Lora-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "Lora-BoldItalic", style: "italic", weight: 700 },
    ],
  },
  "Fira Code": {
    fontFamily: "Fira Code",
    fontPath: "/src/assets/fonts/Fira_Code/static/",
    fontData: [
      { filename: "FiraCode-Light", style: "normal", weight: 300 },
      { filename: "FiraCode-Regular", style: "normal", weight: 400 },
      { filename: "FiraCode-Medium", style: "normal", weight: 500 },
      { filename: "FiraCode-SemiBold", style: "normal", weight: 600 },
      { filename: "FiraCode-Bold", style: "normal", weight: 700 },
    ],
  },
  "Courier Prime": {
    fontFamily: "Courier Prime",
    fontPath: "/src/assets/fonts/Courier_Prime/",
    fontData: [
      { filename: "CourierPrime-Regular", style: "normal", weight: 400 },
      { filename: "CourierPrime-Bold", style: "normal", weight: 700 },
      { filename: "CourierPrime-Italic", style: "italic", weight: 400 },
      { filename: "CourierPrime-BoldItalic", style: "italic", weight: 700 },
    ],
  },
  "Source Code Pro": {
    fontFamily: "Source Code Pro",
    fontPath: "/src/assets/fonts/Source_Code_Pro/static/",
    fontData: [
      { filename: "SourceCodePro-ExtraLight", style: "normal", weight: 200 },
      { filename: "SourceCodePro-Light", style: "normal", weight: 300 },
      { filename: "SourceCodePro-Regular", style: "normal", weight: 400 },
      { filename: "SourceCodePro-Medium", style: "normal", weight: 500 },
      { filename: "SourceCodePro-SemiBold", style: "normal", weight: 600 },
      { filename: "SourceCodePro-Bold", style: "normal", weight: 700 },
      { filename: "SourceCodePro-ExtraBold", style: "normal", weight: 800 },
      { filename: "SourceCodePro-Black", style: "normal", weight: 900 },
      {
        filename: "SourceCodePro-ExtraLightItalic",
        style: "italic",
        weight: 200,
      },
      { filename: "SourceCodePro-LightItalic", style: "italic", weight: 300 },
      { filename: "SourceCodePro-Italic", style: "italic", weight: 400 },
      {
        filename: "SourceCodePro-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "SourceCodePro-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "SourceCodePro-BoldItalic", style: "italic", weight: 700 },
      {
        filename: "SourceCodePro-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      { filename: "SourceCodePro-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  "Playwrite IS": {
    fontFamily: "Playwrite IS",
    fontPath: "/src/assets/fonts/Playwrite_IS/static/",
    fontData: [
      { filename: "PlaywriteIS-Thin", style: "normal", weight: 100 },
      { filename: "PlaywriteIS-ExtraLight", style: "normal", weight: 200 },
      { filename: "PlaywriteIS-Light", style: "normal", weight: 300 },
      { filename: "PlaywriteIS-Regular", style: "normal", weight: 400 },
    ],
  },
  Saira: {
    fontFamily: "Saira",
    fontPath: "/src/assets/fonts/Saira/static/",
    fontData: [
      { filename: "Saira-Thin", style: "normal", weight: 100 },
      { filename: "Saira-ExtraLight", style: "normal", weight: 200 },
      { filename: "Saira-Light", style: "normal", weight: 300 },
      { filename: "Saira-Regular", style: "normal", weight: 400 },
      { filename: "Saira-Medium", style: "normal", weight: 500 },
      { filename: "Saira-SemiBold", style: "normal", weight: 600 },
      { filename: "Saira-Bold", style: "normal", weight: 700 },
      { filename: "Saira-ExtraBold", style: "normal", weight: 800 },
      { filename: "Saira-Black", style: "normal", weight: 900 },
      { filename: "Saira-ThinItalic", style: "italic", weight: 100 },
      {
        filename: "Saira-ExtraLightItalic",
        style: "italic",
        weight: 200,
      },
      { filename: "Saira-LightItalic", style: "italic", weight: 300 },
      { filename: "Saira-Italic", style: "italic", weight: 400 },
      {
        filename: "Saira-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "Saira-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      { filename: "Saira-BoldItalic", style: "italic", weight: 700 },
      {
        filename: "Saira-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      { filename: "Saira-BlackItalic", style: "italic", weight: 900 },
    ],
  },
  Blinker: {
    fontFamily: "Blinker",
    fontPath: "/src/assets/fonts/Blinker/",
    fontData: [
      { filename: "Blinker-Thin", style: "normal", weight: 100 },
      { filename: "Blinker-ExtraLight", style: "normal", weight: 200 },
      { filename: "Blinker-Light", style: "normal", weight: 300 },
      { filename: "Blinker-Regular", style: "normal", weight: 400 },
      { filename: "Blinker-SemiBold", style: "normal", weight: 600 },
      { filename: "Blinker-Bold", style: "normal", weight: 700 },
      { filename: "Blinker-ExtraBold", style: "normal", weight: 800 },
      { filename: "Blinker-Black", style: "normal", weight: 900 },
    ],
  },
  "Saira Condensed": {
    fontFamily: "Saira Condensed",
    fontPath: "/src/assets/fonts/Saira_Condensed/",
    fontData: [
      { filename: "SairaCondensed-Thin", style: "normal", weight: 100 },
      { filename: "SairaCondensed-ExtraLight", style: "normal", weight: 200 },
      { filename: "SairaCondensed-Light", style: "normal", weight: 300 },
      { filename: "SairaCondensed-Regular", style: "normal", weight: 400 },
      { filename: "SairaCondensed-Medium", style: "normal", weight: 500 },
      { filename: "SairaCondensed-SemiBold", style: "normal", weight: 600 },
      { filename: "SairaCondensed-Bold", style: "normal", weight: 700 },
      { filename: "SairaCondensed-ExtraBold", style: "normal", weight: 800 },
      { filename: "SairaCondensed-Black", style: "normal", weight: 900 },
    ],
  },
  "Fira Sans Condensed": {
    fontFamily: "Fira Sans Condensed",
    fontPath: "/src/assets/fonts/Fira_Sans_Condensed/",
    fontData: [
      { filename: "FiraSansCondensed-Thin", style: "normal", weight: 100 },
      {
        filename: "FiraSansCondensed-ExtraLight",
        style: "normal",
        weight: 200,
      },
      { filename: "FiraSansCondensed-Light", style: "normal", weight: 300 },
      { filename: "FiraSansCondensed-Regular", style: "normal", weight: 400 },
      { filename: "FiraSansCondensed-Medium", style: "normal", weight: 500 },
      { filename: "FiraSansCondensed-SemiBold", style: "normal", weight: 600 },
      { filename: "FiraSansCondensed-Bold", style: "normal", weight: 700 },
      { filename: "FiraSansCondensed-ExtraBold", style: "normal", weight: 800 },
      { filename: "FiraSansCondensed-Black", style: "normal", weight: 900 },
      {
        filename: "FiraSansCondensed-ThinItalic",
        style: "italic",
        weight: 100,
      },
      {
        filename: "FiraSansCondensed-ExtraLightItalic",
        style: "italic",
        weight: 200,
      },
      {
        filename: "FiraSansCondensed-LightItalic",
        style: "italic",
        weight: 300,
      },
      { filename: "FiraSansCondensed-Italic", style: "italic", weight: 400 },
      {
        filename: "FiraSansCondensed-MediumItalic",
        style: "italic",
        weight: 500,
      },
      {
        filename: "FiraSansCondensed-SemiBoldItalic",
        style: "italic",
        weight: 600,
      },
      {
        filename: "FiraSansCondensed-BoldItalic",
        style: "italic",
        weight: 700,
      },
      {
        filename: "FiraSansCondensed-ExtraBoldItalic",
        style: "italic",
        weight: 800,
      },
      {
        filename: "FiraSansCondensed-BlackItalic",
        style: "italic",
        weight: 900,
      },
    ],
  },
};

export default fontFacesData;
